services:
  - type: web
    name: ai-music-generator
    env: python
    buildCommand: |
      apt-get update && apt-get install -y fluidsynth
      pip install -r requirements.txt
    startCommand: gunicorn app:app
